### ISSUE TITLE
How do you define your input ?

### ISSUE THREAD

**Issue by Cyrille-AMP** [bitfocus/companion-module-riedel-mediornet#7]
Hello, 

Thanks for your work, 
Just want to know how do you define what is the input1,2,3,4....
I mean, Is the input1 video of companion the input1 video of the lowest node id ? 

Thanks, 
I should have ask you this by MP but I didn't find it,

**Comment by Nico96R** [comment]
Thanks for your question. It got me thinking.
At the moment i number the inputs from 1 to „Number of matrix inputs“.
I just realized that, this means that when a input is added in the middle of the matrix the following inputs will be pushed by one index. This could change the companion layout. So i think i have to change the numbering to the actual matrix index.
Thanks for raising the question 😄

**Comment by Cyrille-AMP** [comment]
Hello, thanks for the reply, now that I have your answer I can bother you with some other... :-D 
The matrix system work with groups that we create, do we must have all the input and output in the same group or can we have multiple groups ?
If I go futher in the brainstorming, could the companion change the group in the matrix, that way we could organize the XY into categories ?

Another thinking...
The matrix system is link to a the mediorwork application not the micron, if you have multiple application running on the network you can have multiple matrix, how companion know which matrix he have to follow ? 

Sorry for all these questions, I just think that your work can be a great help for all of us :-D

**Comment by Nico96R** [comment]
Hey,
sorry for the late reply.
If you mean the Groups in the Mediorworks Matrix, they have no impact on the companion module as far as i know.
The 3rd Party Master provides every Source and destination which has a 3rd Party ID. I can not see a way how you could use the Mediorworks Groups in order to change the matrix organization.
If i didn‘t get your idea, please correct me.

And what do you mean by mediorwork application? Do you mean the apps you can use on some devices?
Like i said before, the module uses the 3rd Party IDs provided by the net master. The IP of the NET Master therefore specifices the matrix. 

I appreciate every new input for improving the module and i hope others benefit from it.

**Comment by Nico96R** [comment]
Is this question answered and can I close the issue?

**Comment by Nico96R** [comment]
with no further update, this issue gets closed.
